[build]
    publish = "dist/storybook/storybook/"
    command = "yarn nx run storybook:build-storybook"

[build.environment]
    NPM_FLAGS="--prefix=/"
    NODE_VERSION = "14.15.3"

[context.branch-deploy]
    command = "npx pnpm run docs"
    publish = "libs/documentations/build/"

[[redirects]]
    from = "/examples/*"
    to = "/examples/"
    status = 301
