[build]
    command = "npm run docs"
    publish = "libs/documentations/build/"

[build.environment]
    NODE_VERSION = "14.19"

[[redirects]]
    from = "/examples/*"
    to = "/examples/"
    status = 301
