[build]
    command = "npx pnpm run docs"
    publish = "libs/documentations/build/"

[build.environment]
    NPM_FLAGS="--prefix=/"
    NODE_VERSION = "14.19"

[context.production.environment]
    NODE_ENV="development"

[[redirects]]
    from = "/examples/*"
    to = "/examples/"
    status = 301
