[build]
    publish = "dist/storybook/storybook"
    command = "yarn nx run storybook:build-storybook
    environment = { NODE_VERSION = "14.15.3" }

[context.branch-deploy]
    base = "libs/documentations"
    command = "npm run build"
    publish = "build/"
