name: Docusaurus
on:
    push:
        branches: [ main ]
jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
                  fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Create local changes and commit
              run: |
                pnpm install
